# Generated by Django 4.2.5 on 2023-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_remove_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
